In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv('insta_comments.csv')
df = df.iloc[:50]
df

article_id     source                                            comment  \
0     insta_3  instagram  Какая прелесть, у меня тоже к этому ровд есть ...   
1     insta_4  instagram              Кому то захотелось это место! 100%!🙌🙌   
2     insta_5  instagram                                     Так неожиданно   
3     insta_6  instagram                                  Кулиб кулиб скяди   
4     insta_7  instagram  😂eng qizig'i yangilik ilovasida Franklinni qar...   
5     insta_8  instagram  👏👏👏отлично подставили ! Место нужно было , вот...   
6     insta_9  instagram                                    😂😂😂😂 не новость   
7    insta_10  instagram  Ого-го это как крупное землетрясение вместе св...   
8    insta_11  instagram  Видимо хотели его с должности снять, вот и сня...   
9    insta_12  instagram  Напишите про котенка в @rano_eco_village, врем...   
10   insta_13  instagram                      Даже доллар в хайране на фото   
11   insta_14  instagram    Сегодня праздник, пожалуй выпью за это событие😂   
12   insta_15  instagram                      Этот взгляд покорил миллиарды   
13   insta_16  instagram  Да да конечно 😂\r\nЗначит все его дела которые...   
14   insta_17  instagram  Почему их лицо не показывают аа если обычный г...   
15   insta_18  instagram  И рас,два,три продолжаем....кто ещё не поделил...   
16   insta_19  instagram  Начальники хочимиятов (хакимы) не попадаются н...   
17   insta_52  instagram                          после GoodBye, WizzAir a!   
18   insta_53  instagram                         Прекрасная авиакомпания!❤️   
19   insta_54  instagram                                😍 Wow супер новости   
20   insta_55  instagram           Ооо круто конечно, направление классные🔥   
21   insta_56  instagram  В официальном канале: Etihad указали с ноября ...   
22   insta_57  instagram  Вот только Виззэир был лоукостером, а Этихад д...   
23   insta_58  instagram  Летала этими авиалиниями из Токио в Лиссабон с...   
24   insta_59  instagram  Если там не будут кормить пловом и самсой, то ...   
25   insta_60  instagram  А собой он не разочарован? Или Израилем например?   
26   insta_61  instagram                                 Ой такой смешной )   
27   insta_62  instagram  Красавчик! Продал ребятам массовое перевооруже...   
28   insta_63  instagram                              Очередные ссанкции)))   
29   insta_64  instagram  Мне так это нравится американское оружие за сч...   
30   insta_65  instagram  Хочет прекратить войну и отправляет оружие где...   
31   insta_66  instagram  Я продолжаю снабжать Украину развед данными че...   
32   insta_67  instagram  Господи откуда в коментах прокремлевские боты ...   
33   insta_68  instagram  Кладу трубку , вместо того чтобы остановить по...   
34   insta_69  instagram                       Да ладно,садомово логово сша   
35   insta_70  instagram                        Доволен, недоволен, смешно.   
36   insta_71  instagram  Толе дело переговоры с Ираном. И потом бомбард...   
37   insta_72  instagram  Рассуждает как царёк, этим доволен, этим не до...   
38   insta_73  instagram  Трамп обещал завершить войну на укр.за сутки,п...   
39   insta_74  instagram  Россия уже поняла, что США просит паузы, чтоб ...   
40   insta_75  instagram  Отличная фраза:\r\nДоговорились о поставке аме...   
41   insta_76  instagram                         Пердеж на голодный желудок   
42   insta_77  instagram  То есть, Россия объявляет перемирие, говорит о...   
43   insta_78  instagram                       Шекспир аплодирует стоя! 😂😂😂   
44   insta_79  instagram  Мы планировали с США переговоры в Омане, о яде...   
45   insta_80  instagram  сделка с лубянкой? с инопланетянами быстрее до...   
46   insta_81  instagram  Америка продаёт оружие, Европа покупает, во вс...   
47   insta_82  instagram   Сам поставляет оружие на Украину а Путин виноват   
48   insta_83  instagram  Интересно, в Америке когда-нибудь будет нормал...   
49   insta_84  instagram             Госпереворот и в

In [22]:
from sklearn.metrics import confusion_matrix, classification_report, f1_score

# example:
y_true = df['true_sentiment']  # replace with your actual column name
y_pred = df['sentiment']  # replace with your actual column name

# Confusion matrix (will be a 2D array)
cm = confusion_matrix(y_true, y_pred, labels=['positive', 'neutral', 'negative'])
print("Confusion Matrix:\n", cm)

# F1 score (macro-averaged for multi-class)
f1 = f1_score(y_true, y_pred, average='macro')
print("F1 Score (macro):", f1)

# Detailed classification report (includes precision, recall, f1 for each class)
print(classification_report(y_true, y_pred))


Confusion Matrix:
 [[ 0  1  5]
 [ 0  5 13]
 [ 0  7 16]]
F1 Score (macro): 0.14247881355932204
              precision    recall  f1-score   support

    negative       0.00      0.00      0.00         1
     neutral       0.00      0.00      0.00         1
    negarive       0.00      0.00      0.00         1
    negative       0.44      0.70      0.54        23
     neutral       0.36      0.28      0.31        18
    positive       0.00      0.00      0.00         6

    accuracy                           0.42        50
   macro avg       0.13      0.16      0.14        50
weighted avg       0.33      0.42      0.36        50



C:\Users\tjwat\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tjwat\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\tjwat\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   article_id      50 non-null     object
 1   source          50 non-null     object
 2   comment         50 non-null     object
 3   clean_comment   50 non-null     object
 4   sentiment       50 non-null     object
 5   true_sentiment  44 non-null     object
dtypes: object(6)
memory usage: 2.5+ KB


In [18]:
print(df['true_sentiment'].apply(type).value_counts())
print(df['sentiment'].apply(type).value_counts())


true_sentiment
<class 'str'>      44
<class 'float'>     6
Name: count, dtype: int64
sentiment
<class 'str'>    50
Name: count, dtype: int64


In [19]:
print(df['true_sentiment'].isna().sum())
print(df['sentiment'].isna().sum())


6
0


In [20]:
# Option A: drop rows with missing or invalid labels
df_clean = df.dropna(subset=['true_sentiment', 'sentiment'])

# Option B: fill NaNs with a default class or string (not ideal for eval)
df['true_sentiment'] = df['true_sentiment'].fillna('neutral')
df['sentiment'] = df['sentiment'].fillna('neutral')


In [21]:
df['true_sentiment'] = df['true_sentiment'].astype(str)
df['sentiment'] = df['sentiment'].astype(str)
